### ISSUE TITLE
[Feature Request]: Single pre or post task able to be run on multiple tasks

### ISSUE THREAD

**Issue by eugenetriguba** [illBeRoy/taskipy#14]
## Request
Hi, I was wondering if it is possible to somehow setup a single pre or post task to run on multiple tasks (or if not since it doesn't appear so, if that behavior being added is even desired for this project)?

## Issue

For example, I have this:
```toml
start_container = "task create_network && task container_pull && task container_up && task setup_container_db"
start_container_build = "task create_network && task build_container && task setup_container_db"
```
And similar tasks for restarting the docker container for building and pulling. However, both of these tasks start and end with the same task. It is only the middle bit that is different. So it can feel a bit verbose to have them be copied over in both places, especially if you have more than two tasks of this sort. 

## Possible Implementation Strategies

With a feature like this, the name of the task, like `pre_test`, would likely no longer only correspond the `test` task. So you would have to signify somehow that this is a pre task but it corresponds to multiple tasks, and it would need some way to signify all the tasks it would run on. I can think of a few ways immediately that this could be implemented: 
  * Left as is so `pre_test` we still know is a pre task, but the string could be checked to see if it is a pre task for multiple tasks or if it is for only the `test` task. I think this could be confusing. 
  * Use a separate name signifier to show that it is a pre task that belongs to multiple tasks. Such as `multiple_pre_[whatever_name]`.
  * You could also just have the key name be whatever and only parse the string. So a valid form here may be something like: `create_network_pretask` where the _pretask ending doesn't mean anything to taskipy here, just showing that it is a pretask to the reader. In this approach, the string value would have to be broken up on three different parts however. You'd have check what kind of task it is so likely 'pre' somewhere, the actual command, and the tasks it runs on, so these three things would likely need to be separated on some sort of delimiter.

Those wouldn't necessarily have to be the implementations, just throwing ideas out there.

**Comment by illBeRoy** [comment]
Hey Eugene!

First of all, thanks for your feedback!

A big inspiration for `taskipy` was `npm` (for nodejs), and the solution there is to actually have separate `pre<X>` scripts, that all point to the same one. e.g.:

```toml
start_container = "task create_network && task container_pull && task container_up && task setup_container_db"
pre_container_build = "task start_container"
pre_test = "task start container"
pre_build = "task start container"
pre_deploy = "task start container"
```

From my experience, this covers the aforementioned case, and is both explicit (each task states that they want to do this in their "pre_task" hook) and coupled (you have a single source of truth task - e.g. `start_container` - and all pre_task hooks depend on it).

That said, if you believe that this solution is not elegant enough, you are welcome to submit a PR with the solution you think is best! I'll make sure to review it ASAP, and if all goes well we'll pull it in :)

Thanks!

**Comment by eugenetriguba** [comment]
After hashing out a partial implementation, I don't actually think this would be that good of a thing to include. While the intent is to introduce the ability for one pre/post hook that could be reused for multiple tasks, such as:

```toml
start_container = "task container_pull && task container_up"
start_container_build = "task build_container"
multi_pre_create_network = "task create_network : start_container, start_container_build"
multi_post_setup_container_db = "task setup_container_db : start_container, start_container_build"
```

it also would then allow multiple pre/post hooks for a single task, which is just weird. It introduces a lot of complexity for something that is harder to read/understand/maintain than just having the bit of duplication.
