### ISSUE TITLE
Support recursive variables

### ISSUE THREAD

**Issue by eugenetriguba** [illBeRoy/taskipy#40]
### Question

With variable support added (#37, #38), should variables be allowed to reference one another recursively?

### Motivation

There are situations where we have a broader variable and a more specific variable that is a superset of the content of the broader variable. This broader and specific variable are then both used throughout the taskipy tasks, but it may be nice to simply reference the broader variable inside of the specific variable rather than repeating it's contents.

### Example

The situation I had encountered was in regards to the filesystem. Let's say we have a project with a `src` directory and a python package inside of it named `package`.

```toml
[tool.taskipy.settings]
use_vars = true

[tool.taskipy.variables]
src_dir = "src"
package_dir = "src/package"
```

With the current variable support implementation, we wouldn't be able to reference our `src_dir` variable inside of our `package_dir` variable because we're only expanding the variables for the top-level task.

With this support, we'd be able to do the following instead:

```toml
[tool.taskipy.settings]
use_vars = true

[tool.taskipy.variables]
src_dir = "src"
package_dir = "{src_dir}/package"
```

And, I would assume, the following should also be supported:

```toml
[tool.taskipy.settings]
use_vars = true

[tool.taskipy.variables]
package_dir = "{src_dir}/package"
src_dir = "src"
```

#### Opt-in setting for backwards compatibility

Since variable support is already present, I don't think we would want to turn on recursive support by default for everyone since that could be a potential breaking change for some. If someone already is using a variable that is using the brackets `{}`, it may cause that variable to no longer have the original meaning because it would now be interpreted as a recursive variable.

For instance, a [jq command](https://stedolan.github.io/jq/tutorial/) such as `curl 'https://api.github.com/repos/stedolan/jq/commits?per_page=5' | jq '.[0] | {message: .commit.message, name: .commit.committer.name}'` would result in `message` interpreted as a format placeholder.

```python
>>> import string
>>> [result[1] for result in string.Formatter().parse("curl 'https://api.github.com/repos/stedolan/jq/commits?per_page=5' | jq '.[0] | {message: .commit.message, name: .commit.committer.name}'")]
['message', None]
>>> [result[1] for result in string.Formatter().parse("{message}")]
['message']
```

So where does that lead us? I assume this must be an opt-in through another setting.

The previous example would then be something along the lines of the following:
```toml
[tool.taskipy.settings]
use_vars = true
enable_recursive_vars = true

[tool.taskipy.variables]
package_dir = "{src_dir}/package"
src_dir = "src"
```

`use_vars` would modify how the tasks are interpreted. `enable_recursive_vars` would modify how the variables are interpreted.

This could also be called `use_recursive_vars`. I'm hesitant on that with how similar the two names would be, but the different areas of behavior they are modifying. There's an argument here that `enable_recursive_vars` isn't really any better in that regard though. I feel like the following would have been nice from the get go:

```toml
[tool.taskipy.settings.tasks]
use_vars = true
```

And then we would have just been able to add:

```toml
[tool.taskipy.settings.variables]
recursive = true
```

We could do something like that, deprecate the global `use_vars` on `[tool.taskipy.settings]` as scheduled for removal for v2, and add a depreciation warning log for it when it is detected. I think it is worth a consideration to namespace those settings.

#### Inline-table support

Should recursive variables be allowed to be turned on per variable, as the current `use_vars` is allowed to be per task? And should it be consistent with the global setting name or would a more concise `recursive` be just fine? 

There's an argument here to be had here that `recursive` is just as descriptive and `enable_recursive_vars` is a bit unnecessarily wordy when you already have the variable context, but there is also an argument here for consistency in the syntax to ease the mental overhead of having to remember which word does what in which contexts.

```toml
[tool.taskipy.variables]
package_dir = { var = "{src_dir}/package", recursive = true }
package_dir2 = "{src_dir}/package" 
src_dir = "src"
```

#### Enhancement setting or used as a more full-featured standalone setting

With the previous examples, we've assumed that we would need both `use_vars` and `enable_recursive_vars` to be in the `[tool.taskipy.settings]` table OR have `use_vars` and on the task AND `recursive` on the variable it is using.

However, there is also an option of simply superseding `use_vars`. Instead of having a `use_vars` setting that can be used in tandem with a `enable_recursive_vars` setting, we could simply have a `use_recursive_vars` setting that does everything that `use_vars` does but also allows for recursive variables.

Globally
```toml
[tool.taskipy.settings]
use_recursive_vars = true

[tool.taskipy.variables]
package_dir = "{src_dir}/package"
src_dir = "src"

[tool.taskipy.tasks]
lint = "flake8 {package_dir}"
```

Inline
```toml
[tool.taskipy.variables]
package_dir = "{src_dir}/package"
src_dir = "src"

[tool.taskipy.tasks]
lint = { cmd = "flake8 {package_dir}", use_recursive_vars = true }
lint2 = { cmd = "flake8 {package_dir}", use_vars = true }
```

In this case, since the `lint` command has a `use_recursive_vars` setting, the `package_dir` variable will be interpreted as `src/package` and the command will end up being run as `flake8 src/package`.

However, with `lint2`, the command is using the `use_vars` setting and so the command will end up being run as `flake8 {src_dir}/package`.

The downside here is that it seems like it would make using the previous variable support with recursive variable support a bit awkward together. It feels like a variable being recursive should be a property of the variable, not of the task.

### Sample Implementation

I had looked briefly into it to see what it would take. For a quick basic implementation (without regard for settings and an assumption of it being on by default), it seems we'd just need to add a couple methods to the `TaskRunner` to have it recursively expand out the variables in place of the current implementation that simply expands out the top most level with `command.format(**self.__project.variables)`.

```python
def __expand_variables(self, command: str) -> str:
        placeholders = self.__get_format_placeholders(command)

        if len(placeholders) == 0:
            return command

        return self.__expand_variables(command.format(**self.__project.variables))

def __get_format_placeholders(self, format_string: str) -> List[str]:
    placeholders = []

    for result in string.Formatter().parse(format_string):
        if result[1] is not None:
            placeholders.append(result[1])

    return placeholders
```

### Conclusion

There were two options proposed here. One is using the recursive variables as an enhancement option to the existing variable support. The other using it as a standalone setting.

There is also the consideration of deprecating `use_vars` on `[tool.taskipy.settings]` and add `use_vars` to `[tool.taskipy.settings.tasks]` and `recursive` to `[tool.taskipy.settings.variables]`. This also keeps the name of the variable setting consistent with the inline syntax. We could also only add the setting to `[tool.taskipy.settings.variables]`. (However, that does open up the question of if `runner` should stay on `[tool.taskipy.settings]` or also move to `[tool.taskipy.settings.tasks]`.)

I would say I'm partial to it as an enhancement setting with the more concise `recursive` syntax on the variable in the inline form and name spacing the settings. Here's a recap of what that would look like:

Both on globally
```toml
[tool.taskipy.settings]
# use_vars = true would also still be allowed here.
tasks = { use_vars = true }
variables = { recursive = true }

[tool.taskipy.variables]
src_dir = "src"
package_dir = "{src_dir}/package"

[tool.taskipy.tasks]
lint = "flake8 {package_dir}"
```

Both inline
```toml
[tool.taskipy.variables]
src_dir = "src"
package_dir = { var = "{src_dir}/package", recursive = true }

[tool.taskipy.tasks]
lint = { cmd = "flake8 {package_dir}", use_vars = true }
```

Global use_vars, inline recursive
```toml
[tool.taskipy.settings]
tasks = { use_vars = true }

[tool.taskipy.variables]
src_dir = "src"
package_dir = { var = "{src_dir}/package", recursive = true }

[tool.taskipy.tasks]
lint = "flake8 {package_dir}"
```

Global recursive, inline use_vars
```toml
[tool.taskipy.settings]
variables = { recursive = true }

[tool.taskipy.variables]
src_dir = "src"
package_dir = "{src_dir}/package"

[tool.taskipy.tasks]
lint = { cmd = "flake8 {package_dir}", use_vars = true }
```

**Comment by illBeRoy** [comment]
Hey! Having variables use one another does make sense in many contexts.

## Product
Product-wise, as per your proposal, I think that the following would be the most approachable:
```toml
[tool.taskipy.variables]
src_dir = "src"
package_dir = { value = "{src_dir}/package", recursive = true }
```

But I am against adding a global configuration for recursive variables.

My reasoning for this product is:
1. As you said, it's not backwards compatible and should not be enabled by default
2. Marking each variable (vs global setting) is the most explicit way to do so: every recursive variable is marked as such, and you won't mistakenly "break" variables because you forgot that they are all recursive.
3. IMO, our configuration scheme is getting more and more complicated, so introducing new settings should be taken seriously and avoided if possible. I think that introducing a new \ additional setting for recursive vars would just make our tool less coherent and harder to follow and understand.

## The Implementation
Resolving variables is very similar to resolving dependencies trees, which is basically:
1. Resolve all possible variables
2. Resolve all variables that depend on them
3. Resolve all variables that depend on them

And so on and so forth.

In our case, this would mean:
1. Resolve all non-recursive variables
2. Iteratively resolve all recursive variables until we either resolve everything, or hit a wall.

Here's a pseudo code for that:
```python
# let's assume "vars" is list of tuples of shape: (key, val, is_recursive)
def resolve_variables(vars):
  resolved_vars = {}
  non_recursive_vars = filter(lambda _, _, is_recursive: not is_recursive, vars)
  recursive_vars = filter(lambda _, _, is_recursive: is_recursive, vars)

  # first thing is to resolve all non-recursive vars. easy.
  for key, val, _ in non_recursive_vars:
    resolved_vars[key] = val

  # second thing would be to resolve all recursive vars.
  # this is an iterative process that ends only when all recursive vars are resolved
  while not empty(recursive_vars):
    # remember how many vars we already resolved
    count_of_already_resolved_vars = len(resolved_vars)
    
    # resolve all resolvable vars by formatting them with vars we already resolved before.
    # any var that depends on vars we haven't already resolved, will throw a KeyError exception, which we ignore,
    # as we hope that it will be resolvable in one of the future iterations.
    for key, val, _ in dict(recursive_vars):
      try:
        resolved_vars[key] = val.format(**resolved_vars)
        recursive_vars.pop(key)
      except KeyError:
        pass
    
    # check if any new vars were resolved in the current iteration.
    # if no new vars were resolved, and the recursive vars list isn't empty, then we hit a wall!
    # this means that we have a circular dependency (a needs b, but b needs a too - either directly or recursively)
    # this cannot be resolved so we need to let the user know
    if count_of_already_resolved_vars == len(resolved_vars):
      raise CircularVariableDependencyException('You have recursive variables that depend on each other! Cannot resolve them.')
      
  return resolved_vars
```

LMK what you think :)
