### ISSUE TITLE
[req] Let tasks access pyproject values

### ISSUE THREAD

**Issue by rafalkrupinski** [illBeRoy/taskipy#50]
Hi

I'd like to have a task that builds a docker image and tags it with the current version. I'm using Poetry, so I could use the version from [tool.poetry]/version.

I know I could use a variable, but I bump the version with `poetry version minor` and it's easy to forget about other places (no need to have version in __init__.py any more).

Thanks!

**Comment by Granitosaurus** [comment]
I can think of 3 ideas how to get this done:

1. We could extend the variable feature with pyproject variables though the variable names would be really long, something like `pyproject.tool.poetry.version` :grimacing:  
2. Alternatively only expand `tool.poetry` section so variables names would be `pyproject.version` but then extending this in the future could be problematic.
3. Give access to pyproject variables to taskipy variable definition:
```
[tool.taskipy.variables]
version = "{pyproject.tool.poetry.version}"

[tool.taskipy.tasks]
version = "echo {version}"
```

**Comment by rafalkrupinski** [comment]
I think `pyproject.tool.poetry.version` is ambiguous or you'd need a special case for poetry to handle tool.poetry as a single and not nested key.
On the other hand, you don't need to use dot as a separator. TOML is a representation of JSON structure - dicts and lists, and Python is not known to use dot to access dict values.
Also, you could replace pyproject with some special character:
```toml
[tool.taskipy.tasks]
version = "echo {$[tool.poetry][version]}"
```

Now, only thing remains to write a parser for it 🫣

**Comment by rafalkrupinski** [comment]
I was able to solve my particular problem, thank to taskipy supporting shell expressions 👍
```toml
[tool.taskipy.tasks]
build = "docker buildx build -t project_name:$(poetry version | cut -d' ' -f2) ."
```
