### ISSUE TITLE
Load environment variables from .env files

### ISSUE THREAD

**Issue by cnschn** [illBeRoy/taskipy#9]
One feature of Pipenv's `[scripts]` I'm missing in taskipy is loading environment variables from `.env` files. This is very useful for local development of applications following the Twelve-Factor App manifesto.

This would be easy to implement using [python-dotenv](https://pypi.org/project/python-dotenv/), basically just calling `load_dotenv()` before running a task.

If you're interested I could put together a PR for this.

**Comment by illBeRoy** [comment]
Hey @cnschn ! Thanks for your input.

I would like to break what I understand from this request into two:
1. Inherent support for the `dotenv` format in `taskipy`
2. The ability to load state before running any task

As for number 1, `python-dotenv` has a CLI that provides a `run` function that loads your `dotenv` file before running a given command. You can it as part as your task, e.g.:
```toml
[tool.taskipy.tasks]
lint_with_env = "dotenv run pylint taskipy"
```

Therefore, despite the fact that `dotenv` is a popular tool, `dotenv run` is simple enough to use, and therefore I would like to keep `taskipy` unopinionated in that regard.

**That said** , regarding point 2, your request made me consider adding a "runner" option to `taskipy`, so you could configure your project to run all tasks using `dotenv` e.g.:
```toml
[tool.taskipy.settings]
runner = "dotenv run"

[tool.taskipy.tasks]
test = "unittest ."
lint = "pylint taskipy"
```

In which case, running both `test` and `lint` will run them using `dotenv`.

What do you think?
